# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('type', models.IntegerField(choices=[(0, 'Country'), (1, 'Province'), (3, 'District'), (2, 'City')], verbose_name='Type')),
                ('parent', models.IntegerField(verbose_name='Parent Number(Associated with yourself)')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('realname', models.CharField(max_length=20, verbose_name='Realname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('face', models.ImageField(blank=True, default='', upload_to='face/%Y/%m/%d', verbose_name='Face')),
                ('url', models.CharField(blank=True, default='', max_length=200, verbose_name='Personal Page')),
                ('about', models.TextField(blank=True, default='', max_length=1000, verbose_name='About Me')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name='Signup Time')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Area', verbose_name='Diqu')),
                ('friend', models.ManyToManyField(related_name='_user_friend_+', to='mvc.User', verbose_name='Friends')),
            ],
            options={
                'verbose_name': 'User Name',
                'verbose_name_plural': 'User Name',
            },
        ),
    ]
