# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='\u6d88\u606f')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Category', verbose_name='\u6765\u6e90')),
            ],
            options={
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '\u6240\u5728\u5730', 'verbose_name_plural': '\u6240\u5728\u5730'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237'},
        ),
        migrations.AlterField(
            model_name='area',
            name='code',
            field=models.CharField(max_length=255, verbose_name='\u4ee3\u7801'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u5730\u540d'),
        ),
        migrations.AlterField(
            model_name='area',
            name='parent',
            field=models.IntegerField(verbose_name='\u7236\u7ea7\u7f16\u53f7\uff08\u5173\u8054\u81ea\u5df1\uff09'),
        ),
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.IntegerField(choices=[(0, '\u56fd\u5bb6'), (2, '\u5e02'), (1, '\u7701'), (3, '\u533a\u53bf')], verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='\u5173\u4e8e\u6211'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addtime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Area', verbose_name='\u5730\u533a'),
        ),
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, default='', upload_to='face/%Y/%m/%d', verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to='mvc.User', verbose_name='\u670b\u53cb'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(max_length=20, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='\u4e2a\u4eba\u4e3b\u9875'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.User', verbose_name='\u53d1\u5e03\u8005'),
        ),
    ]
